name: Build Image & Push to Dockerhub

on:
  schedule:
    - cron: '*/5 * * * *'
    # https://github.blog/changelog/2019-11-01-github-actions-scheduled-jobs-maximum-frequency-is-changing/
  push:
    branches:
      - 'master'

env:
  DOCKERHUB_USERNAME: atomnode
  IMAGE_NAME: coti-node

jobs:
  check-for-new-release:
    name: Check for new release
    runs-on: ubuntu-latest
    steps:
      - name: Compare versions
        id: compare-latest-release-with-readme
        shell: bash
        run: |
          # CURL_ARGS=("-sL" "--connect-timeout" "5" "--max-time" "10" "--retry" "5" "--retry-delay" "0" "--retry-max-time" "40")
          CURL_ARGS=("-sL")
          LATEST_RELEASE=$(curl ${CURL_ARGS[@]} https://api.github.com/repos/coti-io/coti-node/releases/latest | jq ".tag_name" | tr -d '"')
          AVAILABLE_IMAGES=$(curl ${CURL_ARGS[@]} 'https://hub.docker.com/v2/repositories/${{env.DOCKERHUB_USERNAME}}/${{env.IMAGE_NAME}}/tags'|jq '."results"[]["name"]')
          LATEST_IMAGE=$(curl ${CURL_ARGS[@]} 'https://hub.docker.com/v2/repositories/${{env.DOCKERHUB_USERNAME}}/${{env.IMAGE_NAME}}/tags'|jq '."results"[1]["name"]' | tr -d '"')

          # Occasionally LATEST_RELEASE is null for an unknown reason
          count=0
          while [[ $LATEST_RELEASE == "null" ]]; do
            printf 'While loop count: %d\n' "$count"
            LATEST_RELEASE=$(curl ${CURL_ARGS[@]} https://api.github.com/repos/coti-io/coti-node/releases/latest | jq ".tag_name" | tr -d '"')
            (( count++ ))
          done

          IS_NEW_RELEASE=$(if [[ $AVAILABLE_IMAGES == *"$LATEST_RELEASE"* ]]; then echo "❌"; else echo "✅"; fi)

          if [[ $IS_NEW_RELEASE == "✅" ]]; then
            echo "✅ New release found (version $LATEST_RELEASE)."
          elif [[ $IS_NEW_RELEASE == "❌" ]]; then
            echo "✨ No new release found. The latest release is $LATEST_RELEASE and the latest image version is $LATEST_IMAGE. No build needed. This workflow run has completed successfully."
          fi

          echo "IS_NEW_RELEASE=$IS_NEW_RELEASE" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$LATEST_RELEASE" >> $GITHUB_ENV
    outputs:
      is-new-release: ${{env.IS_NEW_RELEASE}}
      release-version: ${{env.RELEASE_VERSION}}

  build-and-push:
    name: Build and push new release
    runs-on: ubuntu-latest
    needs: [check-for-new-release]
    if: ${{ needs.check-for-new-release.outputs.is-new-release == '✅' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{env.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{env.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}},value=${{needs.check-for-new-release.outputs.release-version}}

      - name: Modify coti-node Repository
        run: |
          git clone https://github.com/coti-io/coti-node --branch ${{ needs.check-for-new-release.outputs.release-version }}
          cp update-env coti-node

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./coti-node
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            MODULE=fullnode
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
