name: Build Docker Container & Push to Registry

on:
  schedule:
    - cron: '0 9 * * *'
    # Runs once a day at 9 am
  push:
    branches:
      - 'master'

env:
  DOCKERHUB_USERNAME: atomnode
  IMAGE_NAME: coti-node

jobs:
  check-for-new-release:
    runs-on: ubuntu-latest
    steps:
      - id: get-latest-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: coti-io/coti-node
      - name: Compare versions
        id: compare-latest-release-with-readme
        run: |
          git clone https://github.com/tj-wells/coti-node && cd coti-node
          echo "IS_NEW_RELEASE=$(if [[ ! -z $(grep "${{ steps.get-latest-release.outputs.release }}" "README.md") ]]; then echo "❌"; else echo "✅"; fi)" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${{ steps.get-latest-release.outputs.release }}" >> $GITHUB_ENV
    outputs:
      is-new-release: ${{env.IS_NEW_RELEASE}}
      release-version: ${{env.RELEASE_VERSION}}

  build-and-push:
    runs-on: ubuntu-latest
    needs: [check-for-new-release]
    if: ${{ needs.check-for-new-release.outputs.is-new-release == '✅' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{env.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{env.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}},value=${{needs.check-for-new-release.outputs.release-version}}

      - name: Modify coti-node Repository
        run: |
          new_node_version=$(curl -sL https://api.github.com/repos/coti-io/coti-node/releases/latest | jq -r ".tag_name")
          echo "RELEASE_VERSION=${{ steps.get-latest-release.outputs.release }}" >> $GITHUB_ENV
          git clone https://github.com/coti-io/coti-node --branch $new_node_version
          source_dir=coti-node

          # Modify the Dockerfile
          add_line_1="RUN wget https://www.dropbox.com/s/rpyercs56zmay0z/FullNode1_clusterstamp.csv -P ."
          add_line_2="RUN chown root:root FullNode1_clusterstamp.csv && chgrp root FullNode1_clusterstamp.csv"
          num_lines=$(wc -l < ./$source_dir/Dockerfile)
          sed -i "${num_lines}i\\$add_line_1\\" $source_dir/Dockerfile
          num_lines=$(wc -l < ./$source_dir/Dockerfile)
          sed -i "${num_lines}i\\$add_line_2\\" $source_dir/Dockerfile
          # Make Maven less verbose
          sed -i "s/-am/-am -B/g" $source_dir/Dockerfile

          # Copy update-env
          cp update-env $source_dir

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./coti-node
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            MODULE=fullnode
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
